/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lasky_NativeModule */

#ifndef _Included_com_lasky_NativeModule
#define _Included_com_lasky_NativeModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lasky_NativeModule
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lasky_NativeModule_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_lasky_NativeModule
 * Method:    get_tid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lasky_NativeModule_get_1tid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
